project:
  type: book
  output-dir: ../docs

book:
  title: "Continuing Professional Development"
  author: "rmcmc"
  date: "3/15/2026"
  chapters:
    - index.qmd
    - copulas.qmd
    - cpd_table.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



